package countryCode

import (
	"fmt"
	"strings"

	"github.com/nightin-gale/countryCode/data"
)

// data contains the country code data
// they are generated by ./script/script.go, which reads the data from ./script/countryCode.csv and ./script/moreCountryName.csv

const version = "1.0.1"

func GetCountryCode(name string) (string, error) {
	key := strings.ToUpper(name)
	res, ok := data.NameToCode[key]
	if ok {
		return res, nil
	} else {
		return "", fmt.Errorf("Country Code for %s not found", key)
	}
}

func GetCountryName(code string) (string, error) {
	if len(code) != 2 {
		return "", fmt.Errorf("Country code should be 2 characters")
	}

	key := strings.ToUpper(code)
	res, ok := data.CodeToName[key]
	if ok {
		return res, nil
	} else {
		return "UNKNOWN", nil
	}
}
